name: EnchantmentDisabler
author: opd02
version: '${project.version}'
main: me.opd.enchantmentdisabler.EnchantmentDisablerPlugin
api-version: '1.20'
commands:
  ed:
    description: Open enchant selection GUI or reload config
    usage: "/ed [reload]"
    permission: enchantmentdisabler.admincommand
permissions:
  enchantmentdisabler.admincommand:
    description: Access to /ed GUI
    default: op
  enchantmentdisabler.reload:
    description: Allows reloading the plugin config and caches
    default: op